### ISSUE TITLE
NullPointerException while rendering GUI (dragging around a fuel cell between layers)

### ISSUE THREAD

**Issue by justwlocke** [ThizThizzyDizzy/nc-reactor-generator#167]
Downloaded the most recent beta build, didn't load a save file, fresh reactor.

1. Create a new reactor.
2. Add a fuel cell, with any fuel selected.
3.  Use the select tool select either the input or output ports. 
![image](https://github.com/ThizThizzyDizzy/nc-reactor-generator/assets/84145548/c50a176a-ac87-44ae-a1cc-258baf856dc4)
4. Switch to the move tool to move the port into a corner of the plan.
5. Cry as the error occurs.
![image](https://github.com/ThizThizzyDizzy/nc-reactor-generator/assets/84145548/c958b29f-3ad1-44ed-aefe-ed082d677692)

**Comment by CommanderLouiz** [comment]
Actually, it would seem that moving the fuel cell over any **casing*** is what causes it, not simply the corners

**Comment by justwlocke** [comment]
Actually, it would seem as though moving the fuel cell port over any **casing** triggers the error, not just the corners.

**Comment by Wizzerinus** [comment]
Here's the traceback:
```
java.lang.NullPointerException: Cannot read field "edge" because "b.template.casing" is null
	at net.ncplanner.plannerator.multiblock.overhaul.fissionsfr.OverhaulSFR.canBePlacedInCasingEdge(OverhaulSFR.java:1750)
	at net.ncplanner.plannerator.multiblock.overhaul.fissionsfr.OverhaulSFR.canBePlacedInCasingEdge(OverhaulSFR.java:52)
	at net.ncplanner.plannerator.multiblock.CuboidalMultiblock$1.isSpaceValid(CuboidalMultiblock.java:50)
	at net.ncplanner.plannerator.planner.editor.tool.MoveTool.drawGhosts(MoveTool.java:73)
	at net.ncplanner.plannerator.planner.gui.menu.component.editor.MenuComponentEditorGrid.draw(MenuComponentEditorGrid.java:250)
	at net.ncplanner.plannerator.planner.gui.Component.render2d(Component.java:40)
	at net.ncplanner.plannerator.planner.gui.menu.component.editor.MenuComponentEditorGrid.render2d(MenuComponentEditorGrid.java:77)
	at net.ncplanner.plannerator.planner.gui.menu.component.Scrollable.render2d(Scrollable.java:86)
	at net.ncplanner.plannerator.planner.gui.Component.render2d(Component.java:43)
	at net.ncplanner.plannerator.planner.gui.Menu.render2d(Menu.java:23)
	at net.ncplanner.plannerator.planner.gui.menu.MenuEdit.render2d(MenuEdit.java:471)
	at net.ncplanner.plannerator.planner.gui.GUI.render2d(GUI.java:15)
	at net.ncplanner.plannerator.planner.Core$2.render2d(Core.java:254)
	at net.ncplanner.plannerator.planner.Core.render2d(Core.java:415)
	at net.ncplanner.plannerator.planner.Core.main(Core.java:319)
	at net.ncplanner.plannerator.planner.Main.main(Main.java:88)
```
