### ISSUE TITLE
Generator constantly spawns a new thread that crashes

### ISSUE THREAD

**Issue by Broam** [ThizThizzyDizzy/nc-reactor-generator#26]
Steps to reproduce:

Start program.
Create a new multiblock, Overhaul SFR
Click Pencil to start Editing
Click Generate to go to Generator options
(Options do not seem to matter, so in this example we touch nothing)
Click "Generate" to start generation

Very quickly the GUI with the crash dialog opens up and sucks all the resources from my machine.
The log will immediately fill with this error over and over. In a few seconds it freezes my system.
Go to another vterm, log in, `pkill -9 java`
Wait 15-30 seconds for GNOME to recover from the resource allocation of all those GUI windows

Exceptions is below. The thread GUID changes each time, but the rest is the exact same. NOTE: The thread GUID *never* repeats. The program is spawning a new thread which encounters an exception, then crashes.

I upgraded from 2.15.6 in-place.

Minor Uncaught Error
Jan 04, 2021 7:13:22 PM planner.Core$1 minorError
SEVERE: Error in thread Generation Thread 6ce8bc77-2610-41cb-b21d-5e4260d0dcac:  java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at generator.MultiblockGenerator.lambda$startThread$0(MultiblockGenerator.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at planner.module.RainbowFactorModule$2.doCompare(RainbowFactorModule.java:92)
	at planner.module.RainbowFactorModule$2.doCompare(RainbowFactorModule.java:89)
	at generator.Priority.compare(Priority.java:25)
	at multiblock.Multiblock.isBetterThan(Multiblock.java:632)
	at generator.CoreBasedGenerator.tick(CoreBasedGenerator.java:405)
	at generator.MultiblockGenerator.lambda$startThread$0(MultiblockGenerator.java:62)
	... 1 more

**Comment by Broam** [comment]
I'm still having this happen on 2.16.1

--EXCEPTION OCCURED--
Tue Jan 05 09:51:00 EST 2021
Error in thread Generation Thread 6ea4287b-3a3f-4fee-818b-75932ec8eced:  java.lang.NullPointerException
error=java.lang.RuntimeException
errorMessage=java.lang.NullPointerException
 at generator.MultiblockGenerator.lambda$startThread$0(MultiblockGenerator.java:66)
 at java.lang.Thread.run(Thread.java:748)
causedBy=java.lang.NullPointerException
errorMessage=null
  at planner.module.RainbowFactorModule$2.doCompare(RainbowFactorModule.java:92)
  at planner.module.RainbowFactorModule$2.doCompare(RainbowFactorModule.java:89)
  at generator.Priority.compare(Priority.java:25)
  at multiblock.Multiblock.isBetterThan(Multiblock.java:632)
  at generator.CoreBasedGenerator.finalize(CoreBasedGenerator.java:496)
  at generator.CoreBasedGenerator.tick(CoreBasedGenerator.java:404)
    ...2 more
--END EXCEPTION--
--EXCEPTION OCCURED--
Tue Jan 05 09:51:00 EST 2021
Error in thread Generation Thread f74d3c3f-1730-4860-aeb0-324ab6ef4729:  java.lang.NullPointerException
error=java.lang.RuntimeException
errorMessage=java.lang.NullPointerException
 at generator.MultiblockGenerator.lambda$startThread$0(MultiblockGenerator.java:66)
 at java.lang.Thread.run(Thread.java:748)
causedBy=java.lang.NullPointerException
errorMessage=null
  at planner.module.RainbowFactorModule$2.doCompare(RainbowFactorModule.java:92)
  at planner.module.RainbowFactorModule$2.doCompare(RainbowFactorModule.java:89)
  at generator.Priority.compare(Priority.java:25)
  at multiblock.Multiblock.isBetterThan(Multiblock.java:632)
  at generator.CoreBasedGenerator.finalize(CoreBasedGenerator.java:496)
  at generator.CoreBasedGenerator.tick(CoreBasedGenerator.java:404)
    ...2 more
--END EXCEPTION--
